Repository shipmunkdev/bobax-web, pull requests merged in 2023-03, with the labels that each got.

#4 BobaX-24: Add sample data with TS props for Boba
  src/assets/sampleBobaAPI.tsx
Labels: enhancement

#3 [BobaX-17] Add scoll bar and Add to cart on each drink card
  data_structure.txt
  dj
  package.json
  src/assets/sampleBobaAPI.tsx
  src/components/BobaContainer/index.css
  src/components/BobaContainer/index.tsx
  src/components/Button/index.jsx
  src/components/Card/index.css
  src/components/Card/index.tsx
  src/components/NavigationBar/ShoppingCart.tsx
  src/components/NavigationBar/index.tsx
  src/components/NavigationBar/shoppingcart.css
  src/index.tsx
  src/pages/Home/index.tsx
  yarn.lock
Labels: enhancement

#5 Clean-up, refactor, added imageLink for BobaCard and rename BobaListProps to BobaProps
  src/assets/sampleBobaAPI.tsx
  src/components/BobaContainer/index.tsx
  src/components/Card/index.tsx
  src/components/NavigationBar/ShoppingCart.tsx
  src/components/header/Heading.tsx
  src/pages/Home/index.tsx
Labels: bug

#7 BobaX-19: Add Storybook set-up with TS support
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/components/Button/index.jsx
  src/components/Button/index.tsx
  src/components/Card/index.tsx
  src/stories/Button.stories.tsx
  src/stories/Card.stories.tsx
  src/stories/Introduction.stories.mdx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  yarn.lock
Labels: CI/CD

#9 Bobax 15 boba main page with search filter
  src/components/BobaContainer/index.tsx
  src/components/Card/index.tsx
  src/components/SearchBar/index.tsx
  src/index.tsx
  src/pages/Home/index.tsx
  src/stories/Button.stories.tsx
  src/stories/Card.stories.tsx
  src/stories/Introduction.stories.mdx
  src/types/common/main.d.ts
Labels: enhancement

#13 BOBAX-33: Add README, CONTRIBUTING, and LICENSE
  CONTRIBUTING.md
  LICENSE.md
  README.md
Labels: documentation

#14 BobaX-34: Add Jest unit tests for Button and Card component. Enable CICD for Jest
  .github/workflows/main.yml
  .github/workflows/storybook.yml
  package.json
  src/components/BobaContainer/index.tsx
  src/components/Button/index.test.tsx
  src/components/Card/index.css
  src/components/Card/index.test.tsx
  src/components/Card/index.tsx
  src/pages/Home/index.tsx
Labels: CI/CD

#15 Bobax 16 modal Skeleton
  src/components/BobaContainer/index.tsx
  src/components/Card/index.test.tsx
  src/components/Card/index.tsx
  src/components/Modal/index.tsx
  src/pages/Home/index.tsx
  src/types/common/main.d.ts
Labels: enhancement

#18 Convert .js to .ts and Fix SVG and Searchbox
  .storybook/main.ts
  .storybook/preview.ts
  src/components/BobaContainer/index.tsx
  src/components/Card/index.tsx
  src/components/NavigationBar/ShoppingCart.tsx
  src/components/NavigationBar/ShoppingCartIcon.tsx
  src/components/SearchBar/BinocularIcon.tsx
  src/components/SearchBar/index.tsx
  src/components/header/Heading.tsx
  src/pages/Home/index.tsx
  src/types/common/main.d.ts
Labels: bug

#17 [BobaX-38] Refactor modal into reusable component. Add storybook
  src/components/Card/index.tsx
  src/components/Modal/index.test.tsx
  src/components/Modal/index.tsx
  src/pages/Home/index.tsx
  src/stories/Modal.stories.tsx
Labels: enhancement

#21 Topping and Milk options in Boba Modal
  src/assets/sampleBobaAPI.tsx
  src/components/RadioButton/index.tsx
  src/components/RadioCheckboxGroup/index.tsx
  src/pages/Home/CustomizeBobaModalBody.css
  src/pages/Home/CustomizeBobaModalBody.tsx
  src/pages/Home/index.tsx
  src/stories/RadioCheckbox.stories.tsx
  src/types/common/main.d.ts
Labels: enhancement
